baseURL = 'https://vrmmmmp.github.io/newsite3.0/'
languageCode = 'en-us'
title = '首页'
theme = 'ananke'
publishDir = "docs"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true